tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "openssl@1.1"
brew "autoconf"
brew "boost"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "libffi"
brew "pcre"
brew "readline"
brew "sqlite"
brew "xz"
brew "python@3.8"
brew "glib"
brew "pixman"
brew "cairo"
brew "cmake"
brew "coreutils"
brew "zeromq"
brew "czmq"
brew "jpeg"
brew "libtiff"
brew "erlang"
brew "elixir"
brew "gmp"
brew "gnutls"
brew "pkg-config"
brew "gobject-introspection"
brew "harfbuzz"
brew "ffmpeg"
brew "libtool"
brew "pango"
brew "fontforge"
brew "isl"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "git"
brew "gnupg"
brew "grc"
brew "shared-mime-info"
brew "libheif"
brew "imagemagick", link: false
brew "imagemagick@6"
brew "jp2a"
brew "jpegoptim"
brew "libsodium"
brew "libyaml"
brew "mas"
brew "mysql", link: false
brew "mysql@5.6"
brew "nginx", restart_service: true
brew "php", restart_service: true
brew "pinentry-mac"
brew "pngcrush"
brew "pngpaste"
brew "postgresql"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "spaceman-diff"
brew "spark"
brew "trash"
brew "unrar"
brew "v8"
brew "v8@3.15"
brew "wget"
brew "youtube-dl"
brew "z"
brew "heroku/brew/heroku"
cask "1password"
cask "alfred"
cask "atom"
cask "bartender"
cask "caffeine"
cask "firefox"
cask "google-chrome"
cask "hazel"
cask "imageoptim"
cask "insomnia"
cask "keyboard-maestro"
cask "moom"
cask "qlmarkdown"
cask "textexpander"
cask "toggl"
cask "notion"
mas "Characters", id: 536511979
mas "Contrast", id: 1254981365
mas "Day One", id: 1055511498
mas "Deliveries", id: 924726344
mas "Display Menu", id: 549083868
mas "Fantastical", id: 975937182
mas "Icon Slate", id: 439697913
mas "Spark", id: 1176895641
