# Where apps get installed
cask_args appdir: '/Applications'

# Taps we need to make this all work
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/versions'

# Install Packages
brew 'autoconf'
brew 'icu4c'
brew 'boost'
brew 'xz'
brew 'pkg-config'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'pixman'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'cairo'
brew 'gmp'
brew 'coreutils'
brew 'libsodium'
brew 'zeromq'
brew 'czmq'
brew 'dnsmasq'
brew 'libtool'
brew 'git'
brew 'gobject-introspection'
brew 'harfbuzz'
brew 'pango'
brew 'jpeg'
brew 'libtiff'
brew 'fontforge'
brew 'mpfr'
brew 'libmpc'
brew 'isl'
brew 'gcc'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jpegoptim'
brew 'libyaml'
brew 'openssl'
brew 'mysql'
brew 'nginx'
brew 'node'
brew 'node-build'
brew 'phantomjs'
brew 'pngcrush'
brew 'pngpaste'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'spaceman-diff'
brew 'spark'
brew 'trash'
brew 'unrar'
brew 'v8'
brew 'wget'
brew 'youtube-dl'
brew 'z'
brew 'homebrew/dupes/apple-gcc42'
brew 'homebrew/versions/mysql56'
brew 'homebrew/versions/v8-315'

# Install Apps
cask '1password'
cask 'atom'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'hyper'
cask 'nylas-n1'
cask 'qlmarkdown'
cask 'vlc'
